window.CASES = [
  {
    "id": "cabbage",
    "date": "2026-08-31",
    "category": "먹거리",
    "status": "followup",
    "title": "포름알데히드 배추, 국내 수출은 없었다",
    "summary": "중국 현지 사용 사건 이후, 식약처는 해당 배추의 한국 수출이 없었다고 확인했습니다.",
    "tags": "배추·김치",
    "stage": "해외 현지 사건",
    "origin": "중국",
    "detail": "배추 15건·배추김치 124건의 통관 검사에서 모두 불검출됐습니다. 강화 검사는 계속 진행한다고 발표했습니다.",
    "caution": "중국산 배추 전체의 안전성을 입증하거나, 국내 수입품에서 발암물질이 검출됐다는 뜻은 아닙니다.",
    "publisher": "식약처",
    "sourceType": "공식 발표",
    "url": "https://www.mfds.go.kr/brd/m_1256/view.do?seq=98"
  },
  {
    "id": "peanut",
    "date": "2025-12-16",
    "category": "먹거리",
    "status": "violation",
    "title": "미국산 땅콩버터, 아플라톡신 초과로 회수",
    "summary": "이마트가 수입·판매한 ‘100% 피넛버터 크리미’의 특정 소비기한 제품이 회수됐습니다.",
    "tags": "땅콩버터·이마트",
    "stage": "국내 유통 후 회수",
    "origin": "미국",
    "detail": "회수 대상은 소비기한 2027년 4월 30일, 510g 제품입니다. 총 아플라톡신 기준 초과가 회수 사유입니다.",
    "caution": "해당 소비기한의 제품에 관한 회수입니다. 이마트의 모든 제품이나 미국산 식품 전체에 적용되는 결과가 아닙니다.",
    "publisher": "수입식품정보마루",
    "sourceType": "공식 회수",
    "url": "https://impfood.mfds.go.kr/CFCFF01F02/getCntntsDetail?cntntsMngId=00040&cntntsSn=630325"
  },
  {
    "id": "mushroom",
    "date": "2025-11-06",
    "category": "먹거리",
    "status": "violation",
    "title": "수입 목이버섯에서 잔류농약 기준 초과",
    "summary": "성민통상 수입 제품에서 카벤다짐이 기준을 초과해 판매 중단·회수 조치됐습니다.",
    "tags": "목이버섯·잔류농약",
    "stage": "국내 유통 후 회수",
    "origin": "미확인",
    "detail": "앞서 회수된 목이버섯과 같은 수출업체 제품을 추가 수거·검사하는 과정에서 확인됐습니다.",
    "caution": "이 자료에서 제조국은 확인하지 못했습니다. 회수 사실과 원산지를 구분해 기록했습니다.",
    "publisher": "연합뉴스",
    "sourceType": "언론 보도",
    "url": "https://www.yna.co.kr/amp/view/AKR20251106161300017"
  },
  {
    "id": "kimchi",
    "date": "2021-05-18",
    "category": "먹거리",
    "status": "violation",
    "title": "중국산 김치 15개 제품에서 식중독균 검출",
    "summary": "통관 검사한 289개 제품 중 15개가 여시니아 검출로 부적합 판정을 받았습니다.",
    "tags": "김치·여시니아",
    "stage": "통관 단계 차단",
    "origin": "중국",
    "detail": "식약처가 3월 12일~5월 7일 강화 검사를 실시했습니다. 부적합 제품은 반송·폐기하도록 조치했습니다.",
    "caution": "수입 신고된 제품의 통관 검사 결과입니다. 국내 판매 후 회수된 사건과 구분해야 합니다.",
    "publisher": "MBC",
    "sourceType": "언론 보도",
    "url": "https://imnews.imbc.com/news/2021/society/article/6182597_34873.html"
  },
  {
    "id": "salted-cabbage",
    "date": "2021-05-18",
    "category": "먹거리",
    "status": "violation",
    "title": "절임배추에서 허용되지 않은 보존료 검출",
    "summary": "중국산 절임배추 4개 검사 제품 중 2개에서 데하이드로초산이 검출됐습니다.",
    "tags": "절임배추·보존료",
    "stage": "통관 단계 차단",
    "origin": "중국",
    "detail": "김치 안전성 강화 검사와 같은 발표에 포함된 사례입니다. 해당 제품은 반송·폐기 조치 대상이 됐습니다.",
    "caution": "김치 사건과 같은 검사 발표를 품목별로 나눠 기록했습니다. 사례 수와 기사 수는 다릅니다.",
    "publisher": "MBC",
    "sourceType": "언론 보도",
    "url": "https://imnews.imbc.com/news/2021/society/article/6182597_34873.html"
  },
  {
    "id": "garlic",
    "date": "2021-05-18",
    "category": "먹거리",
    "status": "violation",
    "title": "냉동 다진 마늘, 세균수 기준 초과",
    "summary": "국내 유통 중인 중국산 냉동 다진 마늘 1건에서 부적합이 확인됐습니다.",
    "tags": "다진 마늘·김치 원료",
    "stage": "국내 유통 검사",
    "origin": "중국",
    "detail": "수입 김치와 원재료를 수거·검사한 결과로, 영업자 행정처분이 보도됐습니다.",
    "caution": "김치 완제품과 별도로 원재료 관리에서 확인된 사례입니다.",
    "publisher": "서울신문",
    "sourceType": "언론 보도",
    "url": "https://go.seoul.co.kr/news/newsView.php?id=20210519009013"
  },
  {
    "id": "clam",
    "date": "2019-07-26",
    "category": "먹거리",
    "status": "violation",
    "title": "조개젓에서 A형간염 바이러스 유전자 검출",
    "summary": "중국에서 제조하고 국내에서 추가 가공한 조개젓이 회수·폐기됐습니다.",
    "tags": "조개젓·A형간염",
    "stage": "국내 유통 후 회수",
    "origin": "중국 제조·국내 추가 가공",
    "detail": "병원 직원식당에 제공된 조개젓의 미개봉 검체에서 유전자가 검출돼 역학조사가 진행됐습니다.",
    "caution": "검출 사실과 감염의 인과관계는 구분해야 합니다. 같은 해 다른 전수검사에서는 국산 원료 제품에서도 검출됐습니다.",
    "publisher": "연합뉴스",
    "sourceType": "언론 보도",
    "url": "https://www.yna.co.kr/view/AKR20190726153600017"
  },
  {
    "id": "vezly",
    "date": "2026-06-30",
    "category": "먹거리",
    "status": "confirmed",
    "title": "베즐리 케이크의 중국산 전란액 사용",
    "summary": "현대백화점 베이커리의 원재료 구성이 프리미엄 이미지와 함께 논란이 됐습니다.",
    "tags": "베즐리·현대그린푸드·전란액",
    "stage": "원료 사용 확인",
    "origin": "중국산 계란 원료",
    "detail": "신촌점 케이크·컵케이크 10종과 파운드 선물세트 2종에서 확인됐습니다. 현대그린푸드는 국산 계란의 안정적 확보가 어려워 국산과 수입산을 혼용한다고 설명했습니다.",
    "caution": "전란액은 달걀의 흰자와 노른자를 가공한 원료입니다. 원산지가 표시돼 있으며 안전성 위반이 확인된 사건은 아닙니다. 신세계 사례로 혼동하지 않도록 주의하세요.",
    "publisher": "아주경제",
    "sourceType": "언론 보도",
    "url": "https://www.ajunews.com/view/20260630142049860"
  },
  {
    "id": "spc",
    "date": "2026-07-07",
    "category": "먹거리",
    "status": "confirmed",
    "title": "포켓몬빵 일부 제품에 중국산 전란액",
    "summary": "SPC삼립은 국내 달걀 수급 불안과 가격 상승을 원료 선택의 배경으로 설명했습니다.",
    "tags": "SPC삼립·포켓몬빵·전란액",
    "stage": "원료 사용 확인",
    "origin": "중국산 전란액",
    "detail": "보도에서 식약처는 최근 5년간 중국산 전란액 수입검사 부적합 사례가 없었다고 설명했습니다. SPC는 조류인플루엔자로 인한 수급 불안을 이유로 들었습니다.",
    "caution": "원료 사용 확인과 안전성 위반은 다릅니다. ‘가짜 달걀’이나 ‘발암물질’ 사용이 확인된 사건이 아닙니다.",
    "publisher": "노컷뉴스",
    "sourceType": "언론 보도",
    "url": "https://v.daum.net/v/20260707180300877"
  },
  {
    "id": "shiitake",
    "date": "2025-11-26",
    "category": "원산지",
    "status": "violation",
    "title": "중국산 표고버섯의 국산 둔갑 유통 적발",
    "summary": "원산지 단속기관 협의회에서 농관원의 적발 사례가 공유됐습니다.",
    "tags": "표고버섯·원산지 표시",
    "stage": "원산지 위반 적발",
    "origin": "중국",
    "detail": "관세청이 농관원의 중국산 표고버섯 국산 둔갑 적발을 우수 단속사례로 소개했습니다.",
    "caution": "발표일은 협의회 발표 시점입니다. 정확한 사건 발생일·개별 제품 정보는 이 요약에 포함되지 않았습니다.",
    "publisher": "관세청",
    "sourceType": "공식 발표",
    "url": "https://www.customs.go.kr/kcs/na/ntt/selectNttInfo.do?bbsId=1362&mi=2891&nttSn=10152867"
  },
  {
    "id": "imports",
    "date": "2024-08-01",
    "category": "유통 플랫폼",
    "status": "industry",
    "title": "해외직구에서 중국 비중 61.4%",
    "summary": "2024년 2분기 중국 직구액이 1조 2,373억 원을 기록했습니다.",
    "tags": "알리·테무·해외직구",
    "stage": "통계 발표",
    "origin": "중국 거래 기준",
    "detail": "통계청 자료를 인용한 보도입니다. 중국 직구액은 전년 동기 대비 64.8% 증가했습니다.",
    "caution": "2024년 2분기의 국가별 거래 통계입니다. 현재 점유율이나 알리·테무만의 합산 실적을 뜻하지 않습니다.",
    "publisher": "MBC",
    "sourceType": "통계 인용 보도",
    "url": "https://imnews.imbc.com/news/2024/econo/article/6623049_36452.html"
  },
  {
    "id": "toys",
    "date": "2024-04-25",
    "category": "생활용품",
    "status": "violation",
    "title": "어린이 직구 제품 22개 중 11개 부적합",
    "summary": "알리·테무 판매 제품 검사에서 가소제와 납 등이 기준을 초과했습니다.",
    "tags": "알리·테무·어린이용품",
    "stage": "안전성 검사 부적합",
    "origin": "개별 제조국 미확인",
    "detail": "서울시 검사에서 신발 장식품의 프탈레이트계 가소제가 기준의 최대 348배, 납이 33배 검출됐다고 보도됐습니다.",
    "caution": "선정해 검사한 제품의 결과이며, 플랫폼 전체 제품의 위반율을 나타내지 않습니다.",
    "publisher": "이데일리",
    "sourceType": "언론 보도",
    "url": "https://www.edaily.co.kr/News/Read?mediaCodeNo=257&newsId=02273046638859728"
  },
  {
    "id": "swim",
    "date": "2025-08-01",
    "category": "생활용품",
    "status": "violation",
    "title": "물놀이 용품 33개 중 14개 안전기준 미달",
    "summary": "어린이용 직구 제품에서 화학물질과 내구성·끼임 위험 등이 확인됐습니다.",
    "tags": "알리·테무·물놀이",
    "stage": "안전성 검사 부적합",
    "origin": "개별 제조국 미확인",
    "detail": "서울시가 알리·테무 판매 제품을 조사한 결과입니다. 버클 강도 부족, 유해 화학물질 기준 초과, 삼킴 위험 등이 포함됐습니다.",
    "caution": "각 제품의 위반 항목은 다릅니다. 14개 모두에서 같은 유해물질이 나왔다는 의미는 아닙니다.",
    "publisher": "세계일보",
    "sourceType": "언론 보도",
    "url": "https://www.segye.com/newsView/20250801502636"
  },
  {
    "id": "privacy",
    "date": "2025-05-15",
    "category": "유통 플랫폼",
    "status": "violation",
    "title": "테무, 개인정보보호법 위반으로 제재",
    "summary": "개인정보위가 과징금 13억 6,900만 원과 과태료 1,760만 원을 부과했습니다.",
    "tags": "테무·개인정보",
    "stage": "행정 제재",
    "origin": "중국계 플랫폼",
    "detail": "국내대리인 미지정과 복잡한 회원 탈퇴 절차 등이 확인됐다고 보도됐습니다.",
    "caution": "제품 유해물질이나 제조국 문제와는 별개의 개인정보·소비자 권리 사건입니다.",
    "publisher": "ZDNet Korea",
    "sourceType": "언론 보도",
    "url": "https://zdnet.co.kr/view/?no=20250514221208"
  },
  {
    "id": "alliance",
    "date": "2025-09-18",
    "category": "유통 플랫폼",
    "status": "confirmed",
    "title": "신세계·알리바바, 유통 합작 조건부 승인",
    "summary": "G마켓과 알리익스프레스코리아를 공동 지배하는 기업결합이 승인됐습니다.",
    "tags": "신세계·알리바바·G마켓",
    "stage": "기업결합 조건부 승인",
    "origin": "한국·중국 기업",
    "detail": "공정위는 국내 온라인 해외직구 시장의 경쟁 제한을 우려해 두 회사 간 국내 소비자 정보 차단을 조건으로 부과했습니다.",
    "caution": "기업결합 승인 사실입니다. 모든 신세계 계열사의 중국산 원료 사용을 의미하지 않습니다.",
    "publisher": "공정거래위원회",
    "sourceType": "공식 발표",
    "url": "https://m.korea.kr/briefing/policyBriefingView.do?newsId=156721859"
  },
  {
    "id": "sewing",
    "date": "2024-10-26",
    "category": "제조업",
    "status": "industry",
    "title": "창신동 봉제업, 저가 의류와 경쟁 압박",
    "summary": "중국 플랫폼의 저가 의류 유입과 국내 봉제업의 어려움을 취재한 보도입니다.",
    "tags": "봉제업·의류·쉬인",
    "stage": "산업 현장 취재",
    "origin": "한국·중국",
    "detail": "서울 봉제의복 제조업 종사자는 2020년 7만 875명에서 2023년 6만 266명으로 감소했다고 보도됐습니다.",
    "caution": "이 감소 전체가 중국 플랫폼 때문이라고 인과관계를 단정할 수는 없습니다.",
    "publisher": "동아일보",
    "sourceType": "현장 보도",
    "url": "https://www.donga.com/news/amp/all/20241026/130297990/2"
  },
  {
    "id": "steel",
    "date": "2025-08-28",
    "category": "제조업",
    "status": "violation",
    "title": "중국산 열연후판, 국내 산업 피해 판정",
    "summary": "무역위원회가 덤핑과 덤핑 수입으로 인한 실질적 피해를 판정했습니다.",
    "tags": "철강·열연후판·반덤핑",
    "stage": "무역위 피해 판정",
    "origin": "중국",
    "detail": "무역위는 최종 덤핑방지관세 수준과 일부 업체의 가격약속을 심의했습니다. 공식 발표에서 국내 산업 피해가 확인됩니다.",
    "caution": "소비자 안전성 위반과는 다른 무역구제 사건입니다. 관세 적용의 상세 범위는 원문에서 확인하세요.",
    "publisher": "산업통상부",
    "sourceType": "공식 발표",
    "url": "https://www.motir.go.kr/kor/article/ATCL3f49a5a8c/170856/view"
  },
  {
    "id": "battery",
    "date": "2025-12-01",
    "category": "제조업",
    "status": "industry",
    "title": "한국 배터리의 중국산 소재 의존",
    "summary": "국회예산정책처가 전구체·양극재·흑연 등 핵심 소재 공급망을 분석했습니다.",
    "tags": "배터리·흑연·공급망",
    "stage": "산업 보고서",
    "origin": "한국·중국 공급망",
    "detail": "핵심 소재 단계의 중국 의존과 공급망 재편 부담이 지적됐습니다. 중국 기업과의 합작·공동투자도 분석에 포함됐습니다.",
    "caution": "발표 시점은 2025년 12월이며 정확한 일자는 확인하지 못했습니다. 국산 브랜드와 원재료 원산지는 다를 수 있습니다.",
    "publisher": "국회예산정책처",
    "sourceType": "공식 보고서",
    "url": "https://korea.nabo.go.kr/board/file/down.do?fid=33319012"
  },
  {
    "id": "origin",
    "date": "2025-09-12",
    "category": "원산지",
    "status": "violation",
    "title": "수입 금제품을 한국산으로 위장해 우회수출",
    "summary": "관세청이 2,839억 원 규모 금제품의 원산지 허위 조작 사례를 공개했습니다.",
    "tags": "금 가공제품·우회수출",
    "stage": "원산지 위반 적발",
    "origin": "중국·베트남·인도네시아",
    "detail": "미국의 고관세를 회피하려고 원산지증명서를 한국산으로 허위 조작해 수출한 7개 업체가 적발됐습니다.",
    "caution": "미국 우회수출 사례입니다. 국내 소비자에게 판매된 제품 사건으로 혼동하지 않도록 구분했습니다.",
    "publisher": "관세청",
    "sourceType": "공식 발표",
    "url": "https://www.customs.go.kr/kcs/na/ntt/selectNttInfo.do?bbsId=1362&mi=2891&nttSn=10151545"
  }
];
